version: 1.0.{build}
branches:
  only:
  - master
  - testing
nuget:
  project_feed: true
before_build:
- cmd: nuget restore ./Source/MVC5-Template.sln
build:
  project: ./Source/MVC5-Template.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
  
services:
  - mssql2017

environment:
  COVERALLS_REPO_TOKEN:
    secure: bJPR40E+gfDTIS70CVYTaRGjAh/W7PyORMCM8YNhxL3QpRGp62gTyLBJ7GBB5z5R

after_test: 
        - Source\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[MVC5-Template*]*" -target:"Source\packages\NUnit.ConsoleRunner.3.6.1\tools\nunit3-console.exe" -targetargs:"/domain:single Source\Tests\MVC5-Template.Tests.UnitTests\bin\Debug\MVC5-Template.Tests.UnitTests.dll" -output:cover.xml

        - Source\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover cover.xml