version: 1.0.{build}
branches:
  only:
  - master
nuget:
  project_feed: true
before_build:
- cmd: nuget restore ./Source/MVC5-Template.sln
build:
  project: ./Source/MVC5-Template.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
  
services:
  - mssql2017